## Support Servers/Services
db:
  image: postgres:9.3
  ports:
    - "5432"

## Rails Application Server
web:
  build: .
  volumes:
    - .:/code
  ports:
    - "80:80"
  env_file:
    - .env
    - .env.production
  links:
    - db
